/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/glb/displays/16_9_curved_monitors/16_9_monitor_2_curved_23.5in.glb -t -E -T 
Files: ../../../../public/glb/displays/16_9_curved_monitors/16_9_monitor_2_curved_23.5in.glb [1.77MB] > /Users/diegochuman/Documents/GitHub/deskspacer/src/components/models/displays/16_9_monitor_2_curved_23.5in-transformed.glb [57.93KB] (97%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh;
    Cube001_1: THREE.Mesh;
    Cube001_2: THREE.Mesh;
  };
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.001']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/glb/displays/16_9_curved_monitors/16_9_monitor_2_curved_23.5in-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.326, 2.537, 0]} scale={0.669}>
        <mesh
          geometry={nodes.Cube001.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Cube001_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Cube001_2.geometry}
          material={materials['Material.001']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  '/glb/displays/16_9_curved_monitors/16_9_monitor_2_curved_23.5in-transformed.glb'
);
