/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/malm_desks/malm_desk_white.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/malm_desks/malm_desk_white-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/malm_desks/malm_desk_white.glb [53.97KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/malm_desks/malm_desk_white-transformed.glb [3.63KB] (93%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
  }
  materials: {
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/malm_desks/malm_desk_white-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.596, 6.726, 0]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/malm_desk_white-transformed.glb')
