/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_curved_monitors/21_9_monitor_1_curved_38in.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_curved_monitors/21_9_monitor_1_curved_38in-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_curved_monitors/21_9_monitor_1_curved_38in.glb [4.61MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_curved_monitors/21_9_monitor_1_curved_38in-transformed.glb [103.35KB] (98%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
    Cube003_2: THREE.Mesh
    Cube003_3: THREE.Mesh
  }
  materials: {
    ['Material.078']: THREE.MeshStandardMaterial
    ['Material.079']: THREE.MeshStandardMaterial
    ['Material.080']: THREE.MeshStandardMaterial
    ['Material.081']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/21_9_curved_monitors/21_9_monitor_1_curved_38in-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.021, -1.088, 0.111]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['Material.078']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.079']} />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials['Material.080']} />
        <mesh geometry={nodes.Cube003_3.geometry} material={materials['Material.081']} />
      </group>
    </group>
  )
}

useGLTF.preload('/21_9_monitor_1_curved_38in-transformed.glb')
