/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_curved_monitors/21_9_monitor_2_curved_38in.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_curved_monitors/21_9_monitor_2_curved_38in-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_curved_monitors/21_9_monitor_2_curved_38in.glb [2.19MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_curved_monitors/21_9_monitor_2_curved_38in-transformed.glb [65.95KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder_1: THREE.Mesh
    Cylinder_2: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/21_9_curved_monitors/21_9_monitor_2_curved_38in-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.001, 0.008, 0]}>
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/21_9_monitor_2_curved_38in-transformed.glb')
