/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_curved_monitors/21_9_monitor_1_curved_30in.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_curved_monitors/21_9_monitor_1_curved_30in-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_curved_monitors/21_9_monitor_1_curved_30in.glb [2.25MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_curved_monitors/21_9_monitor_1_curved_30in-transformed.glb [51.69KB] (98%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane025: THREE.Mesh
    Plane025_1: THREE.Mesh
    Plane025_2: THREE.Mesh
    Plane025_3: THREE.Mesh
  }
  materials: {
    ['Material.067']: THREE.MeshStandardMaterial
    ['Material.068']: THREE.MeshStandardMaterial
    ['Material.069']: THREE.MeshStandardMaterial
    ['Material.070']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/21_9_curved_monitors/21_9_monitor_1_curved_30in-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, -1.088, 0.074]}>
        <mesh geometry={nodes.Plane025.geometry} material={materials['Material.067']} />
        <mesh geometry={nodes.Plane025_1.geometry} material={materials['Material.068']} />
        <mesh geometry={nodes.Plane025_2.geometry} material={materials['Material.069']} />
        <mesh geometry={nodes.Plane025_3.geometry} material={materials['Material.070']} />
      </group>
    </group>
  )
}

useGLTF.preload('/21_9_monitor_1_curved_30in-transformed.glb')
