/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_curved_monitors/21_9_monitor_1_curved_34in.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_curved_monitors/21_9_monitor_1_curved_34in-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_curved_monitors/21_9_monitor_1_curved_34in.glb [4.61MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_curved_monitors/21_9_monitor_1_curved_34in-transformed.glb [103.2KB] (98%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube005_2: THREE.Mesh
    Cube005_3: THREE.Mesh
  }
  materials: {
    ['Material.071']: THREE.MeshStandardMaterial
    ['Material.072']: THREE.MeshStandardMaterial
    ['Material.073']: THREE.MeshStandardMaterial
    ['Material.074']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/21_9_curved_monitors/21_9_monitor_1_curved_34in-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.021, -1.088, 0.111]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Material.071']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.072']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['Material.073']} />
        <mesh geometry={nodes.Cube005_3.geometry} material={materials['Material.074']} />
      </group>
    </group>
  )
}

useGLTF.preload('/21_9_monitor_1_curved_34in-transformed.glb')
