/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/regular_desks/regular_desk_2_75.95Dx152.15Wx79.76H.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/regular_desks/regular_desk_2_75.95Dx152.15Wx79.76H-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/regular_desks/regular_desk_2_75.95Dx152.15Wx79.76H.glb [1.14MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/regular_desks/regular_desk_2_75.95Dx152.15Wx79.76H-transformed.glb [87KB] (92%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    Plane: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/regular_desks/regular_desk_2_75.95Dx152.15Wx79.76H-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.002']} position={[-25.302, 0, 17.005]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.003']} position={[-43.083, 22.085, 0.287]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.004']} position={[-43.083, 22.085, -0.456]} scale={[0.468, 0.468, 0.544]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.001']} position={[-25.302, 28.963, 12.754]} />
    </group>
  )
}

useGLTF.preload('/regular_desk_2_75.95Dx152.15Wx79.76H-transformed.glb')
