/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_monitors/16_9_monitor_3_27in.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_monitors/16_9_monitor_3_27in-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_monitors/16_9_monitor_3_27in.glb [2.05MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_monitors/16_9_monitor_3_27in-transformed.glb [58.09KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane016: THREE.Mesh
    Plane016_1: THREE.Mesh
  }
  materials: {
    ['Material.043']: THREE.MeshStandardMaterial
    ['Material.044']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/16_9_monitors/16_9_monitor_3_27in-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.914, -0.227, 0]}>
        <mesh geometry={nodes.Plane016.geometry} material={materials['Material.043']} />
        <mesh geometry={nodes.Plane016_1.geometry} material={materials['Material.044']} />
      </group>
    </group>
  )
}

useGLTF.preload('/16_9_monitor_3_27in-transformed.glb')
