/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_monitors/16_9_monitor_3_22in.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_monitors/16_9_monitor_3_22in-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_monitors/16_9_monitor_3_22in.glb [2.09MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_monitors/16_9_monitor_3_22in-transformed.glb [59.34KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane009: THREE.Mesh
    Plane009_1: THREE.Mesh
  }
  materials: {
    ['Material.035']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/16_9_monitors/16_9_monitor_3_22in-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.914, -0.227, 0]}>
        <mesh geometry={nodes.Plane009.geometry} material={materials['Material.035']} />
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.036']} />
      </group>
    </group>
  )
}

useGLTF.preload('/16_9_monitor_3_22in-transformed.glb')
