/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_monitors/16_9_monitor_3_24in.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_monitors/16_9_monitor_3_24in-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_monitors/16_9_monitor_3_24in.glb [2.09MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_monitors/16_9_monitor_3_24in-transformed.glb [58.95KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane013: THREE.Mesh
    Plane013_1: THREE.Mesh
  }
  materials: {
    ['Material.039']: THREE.MeshStandardMaterial
    ['Material.040']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/16_9_monitors/16_9_monitor_3_24in-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.914, -0.227, 0]}>
        <mesh geometry={nodes.Plane013.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Plane013_1.geometry} material={materials['Material.040']} />
      </group>
    </group>
  )
}

useGLTF.preload('/16_9_monitor_3_24in-transformed.glb')
