/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_monitors/16_9_monitor_4_43in.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_monitors/16_9_monitor_4_43in-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_monitors/16_9_monitor_4_43in.glb [1.1MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_monitors/16_9_monitor_4_43in-transformed.glb [34.44KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001_1: THREE.Mesh
    Plane001_2: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/16_9_monitors/16_9_monitor_4_43in-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-2.093, 0.619, 0]} scale={5.807}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/16_9_monitor_4_43in-transformed.glb')
