/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/full_size_keyboards/full_size_keyboard_orange_black_white.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/full_size_keyboards/full_size_keyboard_orange_black_white-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/full_size_keyboards/full_size_keyboard_orange_black_white.glb [19.27MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/full_size_keyboards/full_size_keyboard_orange_black_white-transformed.glb [559.1KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane011: THREE.Mesh
    Plane011_1: THREE.Mesh
  }
  materials: {
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/full_size_keyboards/full_size_keyboard_orange_black_white-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.657, 0.133, -3.085]}>
        <mesh geometry={nodes.Plane011.geometry} material={materials['Material.034']} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials['Material.035']} />
      </group>
    </group>
  )
}

useGLTF.preload('/full_size_keyboard_orange_black_white-transformed.glb')
