/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/full_size_keyboards/full_size_keyboard_nightrunner.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/full_size_keyboards/full_size_keyboard_nightrunner-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/full_size_keyboards/full_size_keyboard_nightrunner.glb [19.55MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/full_size_keyboards/full_size_keyboard_nightrunner-transformed.glb [564.46KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane010: THREE.Mesh
    Plane010_1: THREE.Mesh
  }
  materials: {
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/full_size_keyboards/full_size_keyboard_nightrunner-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.657, 0.133, -3.085]}>
        <mesh geometry={nodes.Plane010.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Plane010_1.geometry} material={materials['Material.033']} />
      </group>
    </group>
  )
}

useGLTF.preload('/full_size_keyboard_nightrunner-transformed.glb')
