/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/full_size_keyboards/full_size_keyboard_white_grey_red.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/full_size_keyboards/full_size_keyboard_white_grey_red-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/full_size_keyboards/full_size_keyboard_white_grey_red.glb [19.26MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/full_size_keyboards/full_size_keyboard_white_grey_red-transformed.glb [560.21KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane012: THREE.Mesh
    Plane012_1: THREE.Mesh
  }
  materials: {
    ['Material.036']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/full_size_keyboards/full_size_keyboard_white_grey_red-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.657, 0.133, -3.085]}>
        <mesh geometry={nodes.Plane012.geometry} material={materials['Material.036']} />
        <mesh geometry={nodes.Plane012_1.geometry} material={materials['Material.037']} />
      </group>
    </group>
  )
}

useGLTF.preload('/full_size_keyboard_white_grey_red-transformed.glb')
