/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/full_size_keyboards/full_size_keyboard_white.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/full_size_keyboards/full_size_keyboard_white-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/full_size_keyboards/full_size_keyboard_white.glb [13.32MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/full_size_keyboards/full_size_keyboard_white-transformed.glb [661.98KB] (95%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube182: THREE.Mesh
    Cube182_1: THREE.Mesh
  }
  materials: {
    ['Material.114']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/full_size_keyboards/full_size_keyboard_white-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.657, 0.133, -3.085]}>
        <mesh geometry={nodes.Cube182.geometry} material={materials['Material.114']} />
        <mesh geometry={nodes.Cube182_1.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/full_size_keyboard_white-transformed.glb')
