/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/full_size_keyboards/full_size_keyboard_purple_black_red.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/full_size_keyboards/full_size_keyboard_purple_black_red-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/full_size_keyboards/full_size_keyboard_purple_black_red.glb [16.95MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/full_size_keyboards/full_size_keyboard_purple_black_red-transformed.glb [545.72KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Keyboard_Body: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/full_size_keyboards/full_size_keyboard_purple_black_red-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Keyboard_Body.geometry} material={materials.Material} position={[-1.07, 0.447, -3.085]} />
    </group>
  )
}

useGLTF.preload('/full_size_keyboard_purple_black_red-transformed.glb')
