/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/60_keyboards/60_Keyboard_2_orange_black_white.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/60_keyboards/60_Keyboard_2_orange_black_white-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/60_keyboards/60_Keyboard_2_orange_black_white.glb [13.21MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/60_keyboards/60_Keyboard_2_orange_black_white-transformed.glb [459.54KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane008: THREE.Mesh
    Plane008_1: THREE.Mesh
  }
  materials: {
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/60_keyboards/60_Keyboard_2_orange_black_white-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.133, 0.002]}>
        <mesh geometry={nodes.Plane008.geometry} material={materials['Material.020']} />
        <mesh geometry={nodes.Plane008_1.geometry} material={materials['Material.027']} />
      </group>
    </group>
  )
}

useGLTF.preload('/60_Keyboard_2_orange_black_white-transformed.glb')
