/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/60_keyboards/60_Keyboard_2_nightrunner.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/60_keyboards/60_Keyboard_2_nightrunner-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/60_keyboards/60_Keyboard_2_nightrunner.glb [13.5MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/60_keyboards/60_Keyboard_2_nightrunner-transformed.glb [464.86KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane007: THREE.Mesh
    Plane007_1: THREE.Mesh
  }
  materials: {
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/60_keyboards/60_Keyboard_2_nightrunner-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.133, 0.002]}>
        <mesh geometry={nodes.Plane007.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Plane007_1.geometry} material={materials['Material.019']} />
      </group>
    </group>
  )
}

useGLTF.preload('/60_Keyboard_2_nightrunner-transformed.glb')
