/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/60_keyboards/60_Keyboard_2_purple_black_red.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/60_keyboards/60_Keyboard_2_purple_black_red-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/60_keyboards/60_Keyboard_2_purple_black_red.glb [11.32MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/60_keyboards/60_Keyboard_2_purple_black_red-transformed.glb [374.17KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/60_keyboards/60_Keyboard_2_purple_black_red-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.133, 0.002]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/60_Keyboard_2_purple_black_red-transformed.glb')
