/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/60_keyboards/60_Keyboard_2_white_grey_red.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/60_keyboards/60_Keyboard_2_white_grey_red-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/60_keyboards/60_Keyboard_2_white_grey_red.glb [13.2MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/60_keyboards/60_Keyboard_2_white_grey_red-transformed.glb [460.61KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane009: THREE.Mesh
    Plane009_1: THREE.Mesh
  }
  materials: {
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/60_keyboards/60_Keyboard_2_white_grey_red-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.133, 0.002]}>
        <mesh geometry={nodes.Plane009.geometry} material={materials['Material.028']} />
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.029']} />
      </group>
    </group>
  )
}

useGLTF.preload('/60_Keyboard_2_white_grey_red-transformed.glb')
