/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/60_keyboards/60_Keyboard_1_yellow_purple_grad.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/60_keyboards/60_Keyboard_1_yellow_purple_grad-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/60_keyboards/60_Keyboard_1_yellow_purple_grad.glb [12.57MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/60_keyboards/60_Keyboard_1_yellow_purple_grad-transformed.glb [426.57KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane037: THREE.Mesh
    Plane037_1: THREE.Mesh
  }
  materials: {
    ['Material.105']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/60_keyboards/60_Keyboard_1_yellow_purple_grad-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.133, 0.002]}>
        <mesh geometry={nodes.Plane037.geometry} material={materials['Material.105']} />
        <mesh geometry={nodes.Plane037_1.geometry} material={materials['Material.022']} />
      </group>
    </group>
  )
}

useGLTF.preload('/60_Keyboard_1_yellow_purple_grad-transformed.glb')
