/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_31.5in_no_stand.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_31.5in_no_stand-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_31.5in_no_stand.glb [2.05MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_31.5in_no_stand-transformed.glb [59.66KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane006: THREE.Mesh
    Plane006_1: THREE.Mesh
    Plane006_2: THREE.Mesh
  }
  materials: {
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_31.5in_no_stand-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.182, 14.127, 0]}>
        <mesh geometry={nodes.Plane006.geometry} material={materials['Material.029']} />
        <mesh geometry={nodes.Plane006_1.geometry} material={materials['Material.030']} />
        <mesh geometry={nodes.Plane006_2.geometry} material={materials['Material.031']} />
      </group>
    </group>
  )
}

useGLTF.preload('/16_9_monitor_curved_31.5in_no_stand-transformed.glb')
