/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_34in_no_stand.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_34in_no_stand-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_34in_no_stand.glb [2.05MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_34in_no_stand-transformed.glb [60.16KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane007: THREE.Mesh
    Plane007_1: THREE.Mesh
    Plane007_2: THREE.Mesh
  }
  materials: {
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_34in_no_stand-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.182, 14.848, 0]}>
        <mesh geometry={nodes.Plane007.geometry} material={materials['Material.032']} />
        <mesh geometry={nodes.Plane007_1.geometry} material={materials['Material.033']} />
        <mesh geometry={nodes.Plane007_2.geometry} material={materials['Material.034']} />
      </group>
    </group>
  )
}

useGLTF.preload('/16_9_monitor_curved_34in_no_stand-transformed.glb')
