/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_27in_no_stand.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_27in_no_stand-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_27in_no_stand.glb [2.03MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_27in_no_stand-transformed.glb [57.94KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
  }
  materials: {
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/16_9_curved_monitors_no_stand/16_9_monitor_curved_27in_no_stand-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.376, 11.844, 0.008]}>
        <mesh geometry={nodes.Plane.geometry} material={materials['Material.014']} />
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.015']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.016']} />
      </group>
    </group>
  )
}

useGLTF.preload('/16_9_monitor_curved_27in_no_stand-transformed.glb')
