/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/glb/displays/21_9_curved_monitors_no_stand/21_9_monitor_2_curved_34in_no_stand.glb -t -E -T 
Files: ../../../../public/glb/displays/21_9_curved_monitors_no_stand/21_9_monitor_2_curved_34in_no_stand.glb [1.24MB] > /Users/diegochuman/Documents/GitHub/deskspacer/src/components/models/displays/21_9_monitor_2_curved_34in_no_stand-transformed.glb [37.42KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/21_9_monitor_2_curved_34in_no_stand-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 11.598, 0]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('/21_9_monitor_2_curved_34in_no_stand-transformed.glb')
