/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/glb/displays/16_9_curved_monitors/16_9_monitor_curved_27in.glb -t -E -T 
Files: ../../../../public/glb/displays/16_9_curved_monitors/16_9_monitor_curved_27in.glb [3.21MB] > /Users/diegochuman/Documents/GitHub/deskspacer/src/components/models/displays/16_9_monitor_curved_27in-transformed.glb [86.32KB] (97%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Plane004: THREE.Mesh;
    Plane004_1: THREE.Mesh;
    Plane004_2: THREE.Mesh;
  };
  materials: {
    ['Material.008']: THREE.MeshStandardMaterial;
    ['Material.009']: THREE.MeshStandardMaterial;
    ['Material.010']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/glb/displays/16_9_curved_monitors/16_9_monitor_curved_27in-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.376, 2.096, 0.005]}>
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials['Material.008']}
        />
        <mesh
          geometry={nodes.Plane004_1.geometry}
          material={materials['Material.009']}
        />
        <mesh
          geometry={nodes.Plane004_2.geometry}
          material={materials['Material.010']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  '/glb/displays/16_9_curved_monitors/16_9_monitor_curved_27in-transformed.glb'
);
