/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/glb/displays/32_9_monitors/32_9_monitor_curved_49in.glb -t -E -T 
Files: ../../../../public/glb/displays/32_9_monitors/32_9_monitor_curved_49in.glb [5.35MB] > /Users/diegochuman/Documents/GitHub/deskspacer/src/components/models/displays/32_9_monitor_curved_49in-transformed.glb [122.35KB] (98%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Plane031: THREE.Mesh;
    Plane031_1: THREE.Mesh;
    Plane031_2: THREE.Mesh;
  };
  materials: {
    ['Material.118']: THREE.MeshStandardMaterial;
    ['Material.119']: THREE.MeshStandardMaterial;
    ['Material.120']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/glb/displays/32_9_monitors/32_9_monitor_curved_49in-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[1.452, 2.275, 0]}>
        <mesh
          geometry={nodes.Plane031.geometry}
          material={materials['Material.118']}
        />
        <mesh
          geometry={nodes.Plane031_1.geometry}
          material={materials['Material.119']}
        />
        <mesh
          geometry={nodes.Plane031_2.geometry}
          material={materials['Material.120']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  '/glb/displays/32_9_monitors/32_9_monitor_curved_49in-transformed.glb'
);
