/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/glb/displays/16_9_curved_monitors/16_9_monitor_curved_25in.glb -t -E -T 
Files: ../../../../public/glb/displays/16_9_curved_monitors/16_9_monitor_curved_25in.glb [3.24MB] > /Users/diegochuman/Documents/GitHub/deskspacer/src/components/models/displays/16_9_monitor_curved_25in-transformed.glb [87.4KB] (97%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh;
    Plane001_1: THREE.Mesh;
    Plane001_2: THREE.Mesh;
  };
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.007']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/glb/displays/16_9_curved_monitors/16_9_monitor_curved_25in-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.376, 2.096, 0.005]}>
        <mesh
          geometry={nodes.Plane001.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Plane001_1.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Plane001_2.geometry}
          material={materials['Material.007']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  '/glb/displays/16_9_curved_monitors/16_9_monitor_curved_25in-transformed.glb'
);
