/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/glb/displays/32_9_monitors/32_9_monitor_curved_43.4in.glb -t -E -T 
Files: ../../../../public/glb/displays/32_9_monitors/32_9_monitor_curved_43.4in.glb [4.74MB] > /Users/diegochuman/Documents/GitHub/deskspacer/src/components/models/displays/32_9_monitor_curved_43.4in-transformed.glb [125.69KB] (97%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Plane030: THREE.Mesh;
    Plane030_1: THREE.Mesh;
    Plane030_2: THREE.Mesh;
  };
  materials: {
    ['Material.115']: THREE.MeshStandardMaterial;
    ['Material.116']: THREE.MeshStandardMaterial;
    ['Material.117']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/glb/displays/32_9_monitors/32_9_monitor_curved_43.4in-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[1.452, 2.275, 0]}>
        <mesh
          geometry={nodes.Plane030.geometry}
          material={materials['Material.115']}
        />
        <mesh
          geometry={nodes.Plane030_1.geometry}
          material={materials['Material.116']}
        />
        <mesh
          geometry={nodes.Plane030_2.geometry}
          material={materials['Material.117']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  '/glb/displays/32_9_monitors/32_9_monitor_curved_43.4in-transformed.glb'
);
