/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/glb/displays/16_9_curved_monitors/16_9_monitor_curved_31.5in.glb -t -E -T 
Files: ../../../../public/glb/displays/16_9_curved_monitors/16_9_monitor_curved_31.5in.glb [3.27MB] > /Users/diegochuman/Documents/GitHub/deskspacer/src/components/models/displays/16_9_monitor_curved_31.5in-transformed.glb [87.07KB] (97%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Plane010: THREE.Mesh;
    Plane010_1: THREE.Mesh;
    Plane010_2: THREE.Mesh;
  };
  materials: {
    ['Material.020']: THREE.MeshStandardMaterial;
    ['Material.011']: THREE.MeshStandardMaterial;
    ['Material.012']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/glb/displays/16_9_curved_monitors/16_9_monitor_curved_31.5in-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.376, 2.096, 0.005]}>
        <mesh
          geometry={nodes.Plane010.geometry}
          material={materials['Material.020']}
        />
        <mesh
          geometry={nodes.Plane010_1.geometry}
          material={materials['Material.011']}
        />
        <mesh
          geometry={nodes.Plane010_2.geometry}
          material={materials['Material.012']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  '/glb/displays/16_9_curved_monitors/16_9_monitor_curved_31.5in-transformed.glb'
);
