/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/glb/displays/16_9_curved_monitors/16_9_monitor_curved_34in.glb -t -E -T 
Files: ../../../../public/glb/displays/16_9_curved_monitors/16_9_monitor_curved_34in.glb [3.27MB] > /Users/diegochuman/Documents/GitHub/deskspacer/src/components/models/displays/16_9_monitor_curved_34in-transformed.glb [87.39KB] (97%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Plane014: THREE.Mesh;
    Plane014_1: THREE.Mesh;
    Plane014_2: THREE.Mesh;
  };
  materials: {
    ['Material.013']: THREE.MeshStandardMaterial;
    ['Material.027']: THREE.MeshStandardMaterial;
    ['Material.028']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/glb/displays/16_9_curved_monitors/16_9_monitor_curved_34in-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.376, 2.096, 0.005]}>
        <mesh
          geometry={nodes.Plane014.geometry}
          material={materials['Material.013']}
        />
        <mesh
          geometry={nodes.Plane014_1.geometry}
          material={materials['Material.027']}
        />
        <mesh
          geometry={nodes.Plane014_2.geometry}
          material={materials['Material.028']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  '/glb/displays/16_9_curved_monitors/16_9_monitor_curved_34in-transformed.glb'
);
