/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/tkl_keyboards/tkl_keyboard_yellow_grey_black.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/tkl_keyboards/tkl_keyboard_yellow_grey_black-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/tkl_keyboards/tkl_keyboard_yellow_grey_black.glb [16.33MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/tkl_keyboards/tkl_keyboard_yellow_grey_black-transformed.glb [483.54KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane007: THREE.Mesh
    Plane007_1: THREE.Mesh
  }
  materials: {
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/tkl_keyboards/tkl_keyboard_yellow_grey_black-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.657, 0.133, -1.458]}>
        <mesh geometry={nodes.Plane007.geometry} material={materials['Material.016']} />
        <mesh geometry={nodes.Plane007_1.geometry} material={materials['Material.017']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tkl_keyboard_yellow_grey_black-transformed.glb')
