/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/tkl_keyboards/tkl_keyboard_yellow_purple_grad.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/tkl_keyboards/tkl_keyboard_yellow_purple_grad-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/tkl_keyboards/tkl_keyboard_yellow_purple_grad.glb [16.32MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/tkl_keyboards/tkl_keyboard_yellow_purple_grad-transformed.glb [489.4KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane008: THREE.Mesh
    Plane008_1: THREE.Mesh
  }
  materials: {
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/tkl_keyboards/tkl_keyboard_yellow_purple_grad-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.657, 0.133, -1.458]}>
        <mesh geometry={nodes.Plane008.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Plane008_1.geometry} material={materials['Material.019']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tkl_keyboard_yellow_purple_grad-transformed.glb')
