/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/tkl_keyboards/tkl_keyboard_orange_black_white.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/tkl_keyboards/tkl_keyboard_orange_black_white-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/tkl_keyboards/tkl_keyboard_orange_black_white.glb [16.05MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/tkl_keyboards/tkl_keyboard_orange_black_white-transformed.glb [482.49KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane005: THREE.Mesh
    Plane005_1: THREE.Mesh
  }
  materials: {
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/tkl_keyboards/tkl_keyboard_orange_black_white-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.657, 0.133, -1.458]}>
        <mesh geometry={nodes.Plane005.geometry} material={materials['Material.012']} />
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Material.013']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tkl_keyboard_orange_black_white-transformed.glb')
