/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/tkl_keyboards/tkl_keyboard_grey.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/tkl_keyboards/tkl_keyboard_grey-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/tkl_keyboards/tkl_keyboard_grey.glb [15.9MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/tkl_keyboards/tkl_keyboard_grey-transformed.glb [474.71KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane002: THREE.Mesh
    Plane002_1: THREE.Mesh
  }
  materials: {
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/tkl_keyboards/tkl_keyboard_grey-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.657, 0.133, -1.458]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tkl_keyboard_grey-transformed.glb')
