/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/tkl_keyboards/tkl_keyboard_8008.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/tkl_keyboards/tkl_keyboard_8008-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/tkl_keyboards/tkl_keyboard_8008.glb [16MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/tkl_keyboards/tkl_keyboard_8008-transformed.glb [481.23KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
  }
  materials: {
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/tkl_keyboards/tkl_keyboard_8008-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.657, 0.133, -1.458]}>
        <mesh geometry={nodes.Plane003.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.009']} />
      </group>
    </group>
  )
}

useGLTF.preload('/tkl_keyboard_8008-transformed.glb')
