/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/alex_desks/alex_desk_0.79Dx1.7Wx0.73H.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/alex_desks/alex_desk_0.79Dx1.7Wx0.73H-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/alex_desks/alex_desk_0.79Dx1.7Wx0.73H.glb [5.78MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/alex_desks/alex_desk_0.79Dx1.7Wx0.73H-transformed.glb [157.45KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane011: THREE.Mesh
    Plane011_1: THREE.Mesh
    Plane011_2: THREE.Mesh
  }
  materials: {
    ['Material.084']: THREE.MeshStandardMaterial
    ['Material.085']: THREE.MeshStandardMaterial
    ['Material.086']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/alex_desks/alex_desk_0.79Dx1.7Wx0.73H-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-3.042, 27.805, 0]}>
        <mesh geometry={nodes.Plane011.geometry} material={materials['Material.084']} />
        <mesh geometry={nodes.Plane011_1.geometry} material={materials['Material.085']} />
        <mesh geometry={nodes.Plane011_2.geometry} material={materials['Material.086']} />
      </group>
    </group>
  )
}

useGLTF.preload('/alex_desk_0.79Dx1.7Wx0.73H-transformed.glb')
