/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/alex_desks/alex_desk_0.6Dx2Wx0.73H.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/alex_desks/alex_desk_0.6Dx2Wx0.73H-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/alex_desks/alex_desk_0.6Dx2Wx0.73H.glb [5.28MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/alex_desks/alex_desk_0.6Dx2Wx0.73H-transformed.glb [160.03KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane008: THREE.Mesh
    Plane008_1: THREE.Mesh
    Plane008_2: THREE.Mesh
  }
  materials: {
    ['Material.075']: THREE.MeshStandardMaterial
    ['Material.076']: THREE.MeshStandardMaterial
    ['Material.077']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/alex_desks/alex_desk_0.6Dx2Wx0.73H-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-3.042, 28.102, 0]}>
        <mesh geometry={nodes.Plane008.geometry} material={materials['Material.075']} />
        <mesh geometry={nodes.Plane008_1.geometry} material={materials['Material.076']} />
        <mesh geometry={nodes.Plane008_2.geometry} material={materials['Material.077']} />
      </group>
    </group>
  )
}

useGLTF.preload('/alex_desk_0.6Dx2Wx0.73H-transformed.glb')
