/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/alex_desks/alex_desk_1.02Dx1.55Wx0.73H.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/alex_desks/alex_desk_1.02Dx1.55Wx0.73H-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/alex_desks/alex_desk_1.02Dx1.55Wx0.73H.glb [5.79MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/alex_desks/alex_desk_1.02Dx1.55Wx0.73H-transformed.glb [158.42KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane010: THREE.Mesh
    Plane010_1: THREE.Mesh
    Plane010_2: THREE.Mesh
  }
  materials: {
    ['Material.081']: THREE.MeshStandardMaterial
    ['Material.082']: THREE.MeshStandardMaterial
    ['Material.083']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/alex_desks/alex_desk_1.02Dx1.55Wx0.73H-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-3.042, 28.102, 0]}>
        <mesh geometry={nodes.Plane010.geometry} material={materials['Material.081']} />
        <mesh geometry={nodes.Plane010_1.geometry} material={materials['Material.082']} />
        <mesh geometry={nodes.Plane010_2.geometry} material={materials['Material.083']} />
      </group>
    </group>
  )
}

useGLTF.preload('/alex_desk_1.02Dx1.55Wx0.73H-transformed.glb')
