/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mice/mouse_2_12.45Dx8.89Wx5.08H.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mice/mouse_2_12.45Dx8.89Wx5.08H-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mice/mouse_2_12.45Dx8.89Wx5.08H.glb [2.34MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mice/mouse_2_12.45Dx8.89Wx5.08H-transformed.glb [93.05KB] (96%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane002: THREE.Mesh
    Plane002_1: THREE.Mesh
    Plane002_2: THREE.Mesh
  }
  materials: {
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/mice/mouse_2_12.45Dx8.89Wx5.08H-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.32, -0.766, -0.056]}>
        <mesh geometry={nodes.Plane002.geometry} material={materials['Material.024']} />
        <mesh geometry={nodes.Plane002_1.geometry} material={materials['Material.025']} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials['Material.026']} />
      </group>
    </group>
  )
}

useGLTF.preload('/mouse_2_12.45Dx8.89Wx5.08H-transformed.glb')
