/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mice/mouse_3.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mice/mouse_3-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mice/mouse_3.glb [1.23MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mice/mouse_3-transformed.glb [58.29KB] (95%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh
    Cube001_1: THREE.Mesh
    Cube001_2: THREE.Mesh
    Cube001_3: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial004: THREE.MeshStandardMaterial
    PaletteMaterial002: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/mice/mouse_3-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.117, 0.788, 0.009]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials.PaletteMaterial002} />
      </group>
    </group>
  )
}

useGLTF.preload('/mouse_3-transformed.glb')
