/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mice/mouse_1_textured.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mice/mouse_1_textured-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mice/mouse_1_textured.glb [961.77KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mice/mouse_1_textured-transformed.glb [45.07KB] (95%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
    Plane003_2: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/mice/mouse_1_textured-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 1.339, -0.354]} scale={[1.174, 1, 2.116]}>
        <mesh geometry={nodes.Plane003.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('/mouse_1_textured-transformed.glb')
