/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mice/mouse_1_10.41Dx5.59Wx4.06H.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mice/mouse_1_10.41Dx5.59Wx4.06H-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mice/mouse_1_10.41Dx5.59Wx4.06H.glb [1.07MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mice/mouse_1_10.41Dx5.59Wx4.06H-transformed.glb [56.04KB] (95%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane003: THREE.Mesh
    Plane003_1: THREE.Mesh
    Plane003_2: THREE.Mesh
  }
  materials: {
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/mice/mouse_1_10.41Dx5.59Wx4.06H-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.013, 0.069, -0.428]}>
        <mesh geometry={nodes.Plane003.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Plane003_1.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Plane003_2.geometry} material={materials['Material.023']} />
      </group>
    </group>
  )
}

useGLTF.preload('/mouse_1_10.41Dx5.59Wx4.06H-transformed.glb')
