/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_monitors_no_stand/21_9_monitor_2_29in_no_stand.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_monitors_no_stand/21_9_monitor_2_29in_no_stand-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_monitors_no_stand/21_9_monitor_2_29in_no_stand.glb [893.94KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_monitors_no_stand/21_9_monitor_2_29in_no_stand-transformed.glb [22.12KB] (98%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane028: THREE.Mesh
    Plane028_1: THREE.Mesh
    Plane028_2: THREE.Mesh
  }
  materials: {
    ['Material.109']: THREE.MeshStandardMaterial
    ['Material.110']: THREE.MeshStandardMaterial
    ['Material.111']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/21_9_monitors_no_stand/21_9_monitor_2_29in_no_stand-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 10.495, 0]}>
        <mesh geometry={nodes.Plane028.geometry} material={materials['Material.109']} />
        <mesh geometry={nodes.Plane028_1.geometry} material={materials['Material.110']} />
        <mesh geometry={nodes.Plane028_2.geometry} material={materials['Material.111']} />
      </group>
    </group>
  )
}

useGLTF.preload('/21_9_monitor_2_29in_no_stand-transformed.glb')
