/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_monitors_no_stand/21_9_monitor_2_34in_no_stand.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_monitors_no_stand/21_9_monitor_2_34in_no_stand-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_monitors_no_stand/21_9_monitor_2_34in_no_stand.glb [889.41KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_monitors_no_stand/21_9_monitor_2_34in_no_stand-transformed.glb [22.15KB] (98%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane029: THREE.Mesh
    Plane029_1: THREE.Mesh
    Plane029_2: THREE.Mesh
  }
  materials: {
    ['Material.112']: THREE.MeshStandardMaterial
    ['Material.113']: THREE.MeshStandardMaterial
    ['Material.114']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/21_9_monitors_no_stand/21_9_monitor_2_34in_no_stand-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.393, 10.495, 0]}>
        <mesh geometry={nodes.Plane029.geometry} material={materials['Material.112']} />
        <mesh geometry={nodes.Plane029_1.geometry} material={materials['Material.113']} />
        <mesh geometry={nodes.Plane029_2.geometry} material={materials['Material.114']} />
      </group>
    </group>
  )
}

useGLTF.preload('/21_9_monitor_2_34in_no_stand-transformed.glb')
