/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_monitors_no_stand/21_9_monitor_2_25in_no_stand.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_monitors_no_stand/21_9_monitor_2_25in_no_stand-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_monitors_no_stand/21_9_monitor_2_25in_no_stand.glb [889.88KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_monitors_no_stand/21_9_monitor_2_25in_no_stand-transformed.glb [22.13KB] (98%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane027: THREE.Mesh
    Plane027_1: THREE.Mesh
    Plane027_2: THREE.Mesh
  }
  materials: {
    ['Material.106']: THREE.MeshStandardMaterial
    ['Material.107']: THREE.MeshStandardMaterial
    ['Material.108']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/21_9_monitors_no_stand/21_9_monitor_2_25in_no_stand-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 8.55, 0]}>
        <mesh geometry={nodes.Plane027.geometry} material={materials['Material.106']} />
        <mesh geometry={nodes.Plane027_1.geometry} material={materials['Material.107']} />
        <mesh geometry={nodes.Plane027_2.geometry} material={materials['Material.108']} />
      </group>
    </group>
  )
}

useGLTF.preload('/21_9_monitor_2_25in_no_stand-transformed.glb')
