/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_monitors/21_9_monitor_2_34in.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_monitors/21_9_monitor_2_34in-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_monitors/21_9_monitor_2_34in.glb [1.61MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_monitors/21_9_monitor_2_34in-transformed.glb [50.88KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder003: THREE.Mesh
    Cylinder003_1: THREE.Mesh
    Cylinder003_2: THREE.Mesh
    Cylinder003_3: THREE.Mesh
  }
  materials: {
    ['Material.102']: THREE.MeshStandardMaterial
    ['Material.103']: THREE.MeshStandardMaterial
    ['Material.104']: THREE.MeshStandardMaterial
    ['Material.105']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/21_9_monitors/21_9_monitor_2_34in-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.789, 0.022, 0]}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.102']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.103']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.104']} />
        <mesh geometry={nodes.Cylinder003_3.geometry} material={materials['Material.105']} />
      </group>
    </group>
  )
}

useGLTF.preload('/21_9_monitor_2_34in-transformed.glb')
