/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_monitors/21_9_monitor_2_25in.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_monitors/21_9_monitor_2_25in-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_monitors/21_9_monitor_2_25in.glb [1.59MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_monitors/21_9_monitor_2_25in-transformed.glb [50.42KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder002: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    Cylinder002_2: THREE.Mesh
    Cylinder002_3: THREE.Mesh
  }
  materials: {
    ['Material.094']: THREE.MeshStandardMaterial
    ['Material.095']: THREE.MeshStandardMaterial
    ['Material.096']: THREE.MeshStandardMaterial
    ['Material.097']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/21_9_monitors/21_9_monitor_2_25in-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.789, 0.022, 0]}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.094']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.095']} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.096']} />
        <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Material.097']} />
      </group>
    </group>
  )
}

useGLTF.preload('/21_9_monitor_2_25in-transformed.glb')
