/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_monitors/21_9_monitor_2_29in.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_monitors/21_9_monitor_2_29in-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_monitors/21_9_monitor_2_29in.glb [1.63MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_monitors/21_9_monitor_2_29in-transformed.glb [52.45KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane026: THREE.Mesh
    Plane026_1: THREE.Mesh
    Plane026_2: THREE.Mesh
    Plane026_3: THREE.Mesh
  }
  materials: {
    ['Material.098']: THREE.MeshStandardMaterial
    ['Material.099']: THREE.MeshStandardMaterial
    ['Material.100']: THREE.MeshStandardMaterial
    ['Material.101']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/21_9_monitors/21_9_monitor_2_29in-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-1.902, 0.023, 0]}>
        <mesh geometry={nodes.Plane026.geometry} material={materials['Material.098']} />
        <mesh geometry={nodes.Plane026_1.geometry} material={materials['Material.099']} />
        <mesh geometry={nodes.Plane026_2.geometry} material={materials['Material.100']} />
        <mesh geometry={nodes.Plane026_3.geometry} material={materials['Material.101']} />
      </group>
    </group>
  )
}

useGLTF.preload('/21_9_monitor_2_29in-transformed.glb')
