package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"

	"github.com/dcvdiego/deskspacer/backend-go/internal/graph/generated"
	"github.com/dcvdiego/deskspacer/backend-go/internal/models"
)

// AddState is the resolver for the addState field.
func (r *mutationResolver) AddState(ctx context.Context, sharedState string) (*models.SharedState, error) {
	// Use the mutation logic from mutation.go
	return r.Resolver.AddState(ctx, sharedState)
}

// States is the resolver for the states field.
func (r *queryResolver) States(ctx context.Context) ([]*models.SharedState, error) {
	// Use the query logic from query.go
	return r.Resolver.States(ctx)
}

// StatesByID is the resolver for the statesById field.
func (r *queryResolver) StatesByID(ctx context.Context, id string) ([]*models.SharedState, error) {
	// UUID is represented as string in GraphQL, need to parse it
	uuid, err := UnmarshalUUID(id)
	if err != nil {
		return []*models.SharedState{}, nil
	}
	return r.Resolver.StatesById(ctx, uuid)
}

// ID is the resolver for the id field.
func (r *sharedStateResolver) ID(ctx context.Context, obj *models.SharedState) (string, error) {
	// Convert UUID to string for GraphQL
	return obj.ID.String(), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// SharedState returns generated.SharedStateResolver implementation.
func (r *Resolver) SharedState() generated.SharedStateResolver { return &sharedStateResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type sharedStateResolver struct{ *Resolver }
