/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_curved_monitors/16_9_monitor_curved_34in.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_curved_monitors/16_9_monitor_curved_34in-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_curved_monitors/16_9_monitor_curved_34in.glb [3.27MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_curved_monitors/16_9_monitor_curved_34in-transformed.glb [87.39KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane014: THREE.Mesh
    Plane014_1: THREE.Mesh
    Plane014_2: THREE.Mesh
  }
  materials: {
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/16_9_curved_monitors/16_9_monitor_curved_34in-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.376, 2.096, 0.005]}>
        <mesh geometry={nodes.Plane014.geometry} material={materials['Material.013']} />
        <mesh geometry={nodes.Plane014_1.geometry} material={materials['Material.027']} />
        <mesh geometry={nodes.Plane014_2.geometry} material={materials['Material.028']} />
      </group>
    </group>
  )
}

useGLTF.preload('/16_9_monitor_curved_34in-transformed.glb')
