/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/L_shaped_desks/L_shaped_desk_left.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/L_shaped_desks/L_shaped_desk_left-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/L_shaped_desks/L_shaped_desk_left.glb [2.33MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/L_shaped_desks/L_shaped_desk_left-transformed.glb [83.62KB] (96%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane001: THREE.Mesh
    Plane001_1: THREE.Mesh
    Plane001_2: THREE.Mesh
  }
  materials: {
    ['Material.038']: THREE.MeshStandardMaterial
    ['Material.039']: THREE.MeshStandardMaterial
    ['Material.040']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/L_shaped_desks/L_shaped_desk_left-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 29.255, 0]}>
        <mesh geometry={nodes.Plane001.geometry} material={materials['Material.038']} />
        <mesh geometry={nodes.Plane001_1.geometry} material={materials['Material.039']} />
        <mesh geometry={nodes.Plane001_2.geometry} material={materials['Material.040']} />
      </group>
    </group>
  )
}

useGLTF.preload('/L_shaped_desk_left-transformed.glb')
