/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/L_shaped_desks/L_shaped_desk_right.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/L_shaped_desks/L_shaped_desk_right-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/L_shaped_desks/L_shaped_desk_right.glb [2.33MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/L_shaped_desks/L_shaped_desk_right-transformed.glb [84.64KB] (96%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane004: THREE.Mesh
    Plane004_1: THREE.Mesh
    Plane004_2: THREE.Mesh
  }
  materials: {
    ['Material.041']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.043']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/L_shaped_desks/L_shaped_desk_right-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 29.255, 0]}>
        <mesh geometry={nodes.Plane004.geometry} material={materials['Material.041']} />
        <mesh geometry={nodes.Plane004_1.geometry} material={materials['Material.042']} />
        <mesh geometry={nodes.Plane004_2.geometry} material={materials['Material.043']} />
      </group>
    </group>
  )
}

useGLTF.preload('/L_shaped_desk_right-transformed.glb')
