/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/standing_desks/standing_desk_2_72.14Dx139.7Wx75.44H.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/standing_desks/standing_desk_2_72.14Dx139.7Wx75.44H-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/standing_desks/standing_desk_2_72.14Dx139.7Wx75.44H.glb [4.67MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/standing_desks/standing_desk_2_72.14Dx139.7Wx75.44H-transformed.glb [144.26KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube010: THREE.Mesh
    Cube010_1: THREE.Mesh
    Cube010_2: THREE.Mesh
    Cube010_3: THREE.Mesh
  }
  materials: {
    ['Material.087']: THREE.MeshStandardMaterial
    ['Material.088']: THREE.MeshStandardMaterial
    ['Material.089']: THREE.MeshStandardMaterial
    ['standing desk arrow.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/standing_desks/standing_desk_2_72.14Dx139.7Wx75.44H-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 29.469, 0]}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['Material.087']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['Material.088']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials['Material.089']} />
        <mesh geometry={nodes.Cube010_3.geometry} material={materials['standing desk arrow.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/standing_desk_2_72.14Dx139.7Wx75.44H-transformed.glb')
