/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/standing_desks/standing_desk_2_white.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/standing_desks/standing_desk_2_white-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/standing_desks/standing_desk_2_white.glb [3.95MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/standing_desks/standing_desk_2_white-transformed.glb [115.41KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane010: THREE.Mesh
    Plane010_1: THREE.Mesh
    Cube001: THREE.Mesh
    standing_desk_arrow: THREE.Mesh
  }
  materials: {
    ['Material.065']: THREE.MeshStandardMaterial
    ['Material.066']: THREE.MeshStandardMaterial
    ['Material.067']: THREE.MeshStandardMaterial
    ['standing desk arrow.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/standing_desks/standing_desk_2_white-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 30, 0]}>
        <mesh geometry={nodes.Plane010.geometry} material={materials['Material.065']} />
        <mesh geometry={nodes.Plane010_1.geometry} material={materials['Material.066']} />
      </group>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.067']} position={[13.657, 28.424, -18.792]} rotation={[Math.PI / 2, 0.34, 0]} scale={[0.554, 1.139, 0.644]} />
      <mesh geometry={nodes.standing_desk_arrow.geometry} material={materials['standing desk arrow.002']} position={[14.188, 28.533, -18.225]} rotation={[Math.PI / 2, -1.197, -Math.PI / 2]} scale={[0.635, 0.721, 0.721]} />
    </group>
  )
}

useGLTF.preload('/standing_desk_2_white-transformed.glb')
