/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/standing_desks/standing_desk_1_60.45Dx131.32Wx76.96H.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/standing_desks/standing_desk_1_60.45Dx131.32Wx76.96H-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/standing_desks/standing_desk_1_60.45Dx131.32Wx76.96H.glb [13.64MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/standing_desks/standing_desk_1_60.45Dx131.32Wx76.96H-transformed.glb [236.34KB] (98%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    Cube005_2: THREE.Mesh
  }
  materials: {
    ['Material.056']: THREE.MeshStandardMaterial
    ['Material.057']: THREE.MeshStandardMaterial
    ['Material.058']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/standing_desks/standing_desk_1_60.45Dx131.32Wx76.96H-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[9.617, 29.191, 20.391]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Material.056']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.057']} />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials['Material.058']} />
      </group>
    </group>
  )
}

useGLTF.preload('/standing_desk_1_60.45Dx131.32Wx76.96H-transformed.glb')
