/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/standing_desks/standing_desk_2_light-wood.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/standing_desks/standing_desk_2_light-wood-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/standing_desks/standing_desk_2_light-wood.glb [6.46MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/standing_desks/standing_desk_2_light-wood-transformed.glb [247.59KB] (96%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane009: THREE.Mesh
    Plane009_1: THREE.Mesh
    Plane009_2: THREE.Mesh
    Plane009_3: THREE.Mesh
  }
  materials: {
    ['Material.062']: THREE.MeshStandardMaterial
    ['Material.063']: THREE.MeshStandardMaterial
    ['Material.064']: THREE.MeshStandardMaterial
    ['standing desk arrow']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/standing_desks/standing_desk_2_light-wood-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 30, 0]}>
        <mesh geometry={nodes.Plane009.geometry} material={materials['Material.062']} />
        <mesh geometry={nodes.Plane009_1.geometry} material={materials['Material.063']} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials['Material.064']} />
        <mesh geometry={nodes.Plane009_3.geometry} material={materials['standing desk arrow']} />
      </group>
    </group>
  )
}

useGLTF.preload('/standing_desk_2_light-wood-transformed.glb')
