/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_curved_monitors_no_stand/21_9_monitor_1_curved_34in_no_stand.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_curved_monitors_no_stand/21_9_monitor_1_curved_34in_no_stand-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/21_9_curved_monitors_no_stand/21_9_monitor_1_curved_34in_no_stand.glb [1.47MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/21_9_curved_monitors_no_stand/21_9_monitor_1_curved_34in_no_stand-transformed.glb [30.7KB] (98%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube004: THREE.Mesh
    Cube004_1: THREE.Mesh
  }
  materials: {
    ['Material.090']: THREE.MeshStandardMaterial
    ['Material.091']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/21_9_curved_monitors_no_stand/21_9_monitor_1_curved_34in_no_stand-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, 9.433, 2.202]}>
        <mesh geometry={nodes.Cube004.geometry} material={materials['Material.090']} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials['Material.091']} />
      </group>
    </group>
  )
}

useGLTF.preload('/21_9_monitor_1_curved_34in_no_stand-transformed.glb')
