/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/linnmon_desks/linnmon_desk_0.61Dx1.2Wx0.77H.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/linnmon_desks/linnmon_desk_0.61Dx1.2Wx0.77H-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/linnmon_desks/linnmon_desk_0.61Dx1.2Wx0.77H.glb [193.14KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/linnmon_desks/linnmon_desk_0.61Dx1.2Wx0.77H-transformed.glb [7.56KB] (96%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane006: THREE.Mesh
    Plane006_1: THREE.Mesh
  }
  materials: {
    ['Material.046']: THREE.MeshStandardMaterial
    ['Material.047']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/linnmon_desks/linnmon_desk_0.61Dx1.2Wx0.77H-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 29.912, 0]}>
        <mesh geometry={nodes.Plane006.geometry} material={materials['Material.046']} />
        <mesh geometry={nodes.Plane006_1.geometry} material={materials['Material.047']} />
      </group>
    </group>
  )
}

useGLTF.preload('/linnmon_desk_0.61Dx1.2Wx0.77H-transformed.glb')
