/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/output_platform_desks/output_platform_desk.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/output_platform_desks/output_platform_desk-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/desks/output_platform_desks/output_platform_desk.glb [13.69MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/desks/output_platform_desks/output_platform_desk-transformed.glb [56.56KB] (100%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
  }
  materials: {
    ['Material.050']: THREE.MeshStandardMaterial
    ['Material.051']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/desks/output_platform_desks/output_platform_desk-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[11.643, 29.16, 0]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials['Material.050']} />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials['Material.051']} />
      </group>
    </group>
  )
}

useGLTF.preload('/output_platform_desk-transformed.glb')
