/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/medium_rgb_mousepad.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/medium_rgb_mousepad-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/medium_rgb_mousepad.glb [555.88KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/medium_rgb_mousepad-transformed.glb [29.26KB] (95%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube001: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/mousepads/medium_rgb_mousepad-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.002']} scale={[6.041, 0.087, 7.294]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} scale={[6.424, 0.107, 18.208]} />
    </group>
  )
}

useGLTF.preload('/medium_rgb_mousepad-transformed.glb')
