/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/small_qck_mousepad_21.34Dx24.89W.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/small_qck_mousepad_21.34Dx24.89W-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/small_qck_mousepad_21.34Dx24.89W.glb [236.58KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/small_qck_mousepad_21.34Dx24.89W-transformed.glb [7.93KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube030: THREE.Mesh
    Cube030_1: THREE.Mesh
  }
  materials: {
    ['Material.028']: THREE.MeshStandardMaterial
    ['knockoff steelseries logo.003']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/mousepads/small_qck_mousepad_21.34Dx24.89W-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube030.geometry} material={materials['Material.028']} />
      <mesh geometry={nodes.Cube030_1.geometry} material={materials['knockoff steelseries logo.003']} />
    </group>
  )
}

useGLTF.preload('/small_qck_mousepad_21.34Dx24.89W-transformed.glb')
