/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/large_qck_mousepad_39.88Dx44.96W.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/large_qck_mousepad_39.88Dx44.96W-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/large_qck_mousepad_39.88Dx44.96W.glb [236.24KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/large_qck_mousepad_39.88Dx44.96W-transformed.glb [7.92KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube026: THREE.Mesh
    Cube026_1: THREE.Mesh
  }
  materials: {
    ['Material.019']: THREE.MeshStandardMaterial
    ['knockoff steelseries logo']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/mousepads/large_qck_mousepad_39.88Dx44.96W-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube026.geometry} material={materials['Material.019']} />
      <mesh geometry={nodes.Cube026_1.geometry} material={materials['knockoff steelseries logo']} />
    </group>
  )
}

useGLTF.preload('/large_qck_mousepad_39.88Dx44.96W-transformed.glb')
