/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/XXL_qck_mousepad.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/XXL_qck_mousepad-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/XXL_qck_mousepad.glb [234.4KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/XXL_qck_mousepad-transformed.glb [7.9KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube003: THREE.Mesh
    Cube003_1: THREE.Mesh
  }
  materials: {
    ['Material.027']: THREE.MeshStandardMaterial
    ['knockoff steelseries logo.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/mousepads/XXL_qck_mousepad-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.027']} />
      <mesh geometry={nodes.Cube003_1.geometry} material={materials['knockoff steelseries logo.002']} />
    </group>
  )
}

useGLTF.preload('/XXL_qck_mousepad-transformed.glb')
