/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/medium_rgb_mousepad_31.75Dx37.85W.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/medium_rgb_mousepad_31.75Dx37.85W-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/medium_rgb_mousepad_31.75Dx37.85W.glb [666.1KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/medium_rgb_mousepad_31.75Dx37.85W-transformed.glb [31.99KB] (95%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube028: THREE.Mesh
    Cube028_1: THREE.Mesh
  }
  materials: {
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/mousepads/medium_rgb_mousepad_31.75Dx37.85W-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[6.041, 7.294, 0.087]}>
        <mesh geometry={nodes.Cube028.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.Cube028_1.geometry} material={materials['Material.011']} />
      </group>
    </group>
  )
}

useGLTF.preload('/medium_rgb_mousepad_31.75Dx37.85W-transformed.glb')
