/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/big_mousepad_31.75Dx91.44W.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/big_mousepad_31.75Dx91.44W-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/big_mousepad_31.75Dx91.44W.glb [674.48KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/big_mousepad_31.75Dx91.44W-transformed.glb [28.78KB] (96%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube024: THREE.Mesh
    Cube024_1: THREE.Mesh
  }
  materials: {
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/mousepads/big_mousepad_31.75Dx91.44W-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[6.041, 17.895, 0.087]}>
        <mesh geometry={nodes.Cube024.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Cube024_1.geometry} material={materials['Material.007']} />
      </group>
    </group>
  )
}

useGLTF.preload('/big_mousepad_31.75Dx91.44W-transformed.glb')
