/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/medium_qck_mousepad_26.92Dx32W.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/medium_qck_mousepad_26.92Dx32W-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/mousepads/medium_qck_mousepad_26.92Dx32W.glb [236.89KB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/mousepads/medium_qck_mousepad_26.92Dx32W-transformed.glb [7.82KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube027: THREE.Mesh
    Cube027_1: THREE.Mesh
  }
  materials: {
    ['Material.020']: THREE.MeshStandardMaterial
    ['knockoff steelseries logo.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/mousepads/medium_qck_mousepad_26.92Dx32W-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube027.geometry} material={materials['Material.020']} />
      <mesh geometry={nodes.Cube027_1.geometry} material={materials['knockoff steelseries logo.001']} />
    </group>
  )
}

useGLTF.preload('/medium_qck_mousepad_26.92Dx32W-transformed.glb')
