/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/work_keyboards/slim_keyboard.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/work_keyboards/slim_keyboard-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/keyboards/work_keyboards/slim_keyboard.glb [13.03MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/keyboards/work_keyboards/slim_keyboard-transformed.glb [406KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    Plane_3: THREE.Mesh
    Plane_4: THREE.Mesh
  }
  materials: {
    PaletteMaterial002: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    PaletteMaterial003: THREE.MeshStandardMaterial
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/keyboards/work_keyboards/slim_keyboard-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane_1.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Plane_2.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.Plane_3.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Plane_4.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('/slim_keyboard-transformed.glb')
