/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../../../public/glb/desks/standing-desks/standing_desk_2-28.4Dx55Wx29.7H.glb -t -E -T 
Files: ../../../../public/glb/desks/standing-desks/standing_desk_2-28.4Dx55Wx29.7H.glb [4.67MB] > /Users/diegochuman/Documents/GitHub/deskspacer/src/components/models/desks/standing_desk_2-28.4Dx55Wx29.7H-transformed.glb [144.26KB] (97%)
*/

import * as THREE from 'three';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Cube010: THREE.Mesh;
    Cube010_1: THREE.Mesh;
    Cube010_2: THREE.Mesh;
    Cube010_3: THREE.Mesh;
  };
  materials: {
    ['Material.087']: THREE.MeshStandardMaterial;
    ['Material.088']: THREE.MeshStandardMaterial;
    ['Material.089']: THREE.MeshStandardMaterial;
    ['standing desk arrow.001']: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/glb/desks/standing-desks/standing_desk_2-28.4Dx55Wx29.7H-transformed.glb'
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0, 29.469, 0]}>
        <mesh
          geometry={nodes.Cube010.geometry}
          material={materials['Material.087']}
        />
        <mesh
          geometry={nodes.Cube010_1.geometry}
          material={materials['Material.088']}
        />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials['Material.089']}
        />
        <mesh
          geometry={nodes.Cube010_3.geometry}
          material={materials['standing desk arrow.001']}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  '/glb/desks/standing-desks/standing_desk_2-28.4Dx55Wx29.7H-transformed.glb'
);
