/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/32_9_monitors_no_stand/32_9_monitor_curved_43.4in_no_stand.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/32_9_monitors_no_stand/32_9_monitor_curved_43.4in_no_stand-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/32_9_monitors_no_stand/32_9_monitor_curved_43.4in_no_stand.glb [1.49MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/32_9_monitors_no_stand/32_9_monitor_curved_43.4in_no_stand-transformed.glb [37.93KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane032: THREE.Mesh
    Plane032_1: THREE.Mesh
  }
  materials: {
    ['Material.121']: THREE.MeshStandardMaterial
    ['Material.122']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/32_9_monitors_no_stand/32_9_monitor_curved_43.4in_no_stand-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.506, 10.822, 0]}>
        <mesh geometry={nodes.Plane032.geometry} material={materials['Material.121']} />
        <mesh geometry={nodes.Plane032_1.geometry} material={materials['Material.122']} />
      </group>
    </group>
  )
}

useGLTF.preload('/32_9_monitor_curved_43.4in_no_stand-transformed.glb')
