/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_monitors_no_stand/16_9_monitor_3_31.5in_no_stand.glb -t -E -T -o /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_monitors_no_stand/16_9_monitor_3_31.5in_no_stand-transformed.tsx 
Files: /Users/diegochuman/Documents/GitHub/deskspacer/frontend/public/glb/displays/16_9_monitors_no_stand/16_9_monitor_3_31.5in_no_stand.glb [1.79MB] > /Users/diegochuman/Documents/GitHub/deskspacer/frontend/src/components/models/displays/16_9_monitors_no_stand/16_9_monitor_3_31.5in_no_stand-transformed.glb [48.92KB] (97%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane024: THREE.Mesh
    Plane024_1: THREE.Mesh
  }
  materials: {
    ['Material.061']: THREE.MeshStandardMaterial
    ['Material.062']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/displays/16_9_monitors_no_stand/16_9_monitor_3_31.5in_no_stand-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.895, 11.678, -0.023]}>
        <mesh geometry={nodes.Plane024.geometry} material={materials['Material.061']} />
        <mesh geometry={nodes.Plane024_1.geometry} material={materials['Material.062']} />
      </group>
    </group>
  )
}

useGLTF.preload('/16_9_monitor_3_31.5in_no_stand-transformed.glb')
